// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

import (
	"github.com/gogf/gf/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id       string      `orm:"id"        json:"id"`       //
	Email    string      `orm:"email"     json:"email"`    //
	Phone    string      `orm:"phone"     json:"phone"`    //
	Role     string      `orm:"role"      json:"role"`     //
	Disabled bool        `orm:"disabled"  json:"disabled"` //
	Password string      `orm:"password"  json:"password"` //
	CreateAt *gtime.Time `orm:"create_at" json:"createAt"` //
	UpdateAt *gtime.Time `orm:"update_at" json:"updateAt"` //
}
