GET http://localhost:8299/user/profile
Accept: application/json
Cookie: gfsessionid=14sg9d5h08fw40cewawkwym2c8100gpw

###
POST http://localhost:8299/user/sign-in
Content-Type: application/json

{
  "Passport":"Spike2@gmail.com",
  "Password":"123456"
}


###
POST http://icosmonaut.xyz:8199/api/v1/user/sign-up
Content-Type: application/json

{
  "email":"Spike12345@gmail.com",
  "password":"123456"
}

