# HTTP Server
[server]
	Address     = ":8199"
	ServerRoot  = "public"
	ServerAgent = "cosmonaut"
	LogPath     = "/tmp/log/cosmonaut/server"

# Logger.
[logger]
    Path        = "/tmp/log/cosmonaut"
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["{{", "}}"]
    [viewer.confirm_sign_up]
        defaultFile = "email/confirm_sign_up.html"

# Database.
[database]
    link  = "pgsql: user=postgres password=qwe123 host=127.0.0.1 port=5432 dbname=postgres sslmode=disable"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "/tmp/log/cosmonaut/sql"
        Level  = "all"
        Stdout = true

[gfcli]
    [[gfcli.gen.dao]]
        link   = "pgsql: user=postgres password=qwe123 host=127.0.0.1 port=5432 dbname=postgres sslmode=disable"
        tables = ""