// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"cosmonaut_api/app/dao/internal"
)

// emailConfirmDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type emailConfirmDao struct {
	*internal.EmailConfirmDao
}

var (
	// EmailConfirm is globally public accessible object for table email_confirm operations.
	EmailConfirm emailConfirmDao
)

func init() {
	EmailConfirm = emailConfirmDao{
		internal.NewEmailConfirmDao(),
	}
}

// Fill with you ideas below.
