// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"cosmonaut_api/app/dao/internal"
)

// postDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type postDao struct {
	*internal.PostDao
}

var (
	// Post is globally public accessible object for table post operations.
	Post postDao
)

func init() {
	Post = postDao{
		internal.NewPostDao(),
	}
}

// Fill with you ideas below.
