// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"cosmonaut_api/app/dao/internal"
)

// profileDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type profileDao struct {
	*internal.ProfileDao
}

var (
	// Profile is globally public accessible object for table profile operations.
	Profile profileDao
)

func init() {
	Profile = profileDao{
		internal.NewProfileDao(),
	}
}

// Fill with you ideas below.
