// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"cosmonaut_api/app/dao/internal"
)

// tEDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type tEDao struct {
	*internal.TEDao
}

var (
	// TE is globally public accessible object for table t_e operations.
	TE tEDao
)

func init() {
	TE = tEDao{
		internal.NewTEDao(),
	}
}

// Fill with you ideas below.
