// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"cosmonaut_api/app/dao/internal"
)

// userPostLikeDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type userPostLikeDao struct {
	*internal.UserPostLikeDao
}

var (
	// UserPostLike is globally public accessible object for table user_post_like operations.
	UserPostLike userPostLikeDao
)

func init() {
	UserPostLike = userPostLikeDao{
		internal.NewUserPostLikeDao(),
	}
}

// Fill with you ideas below.
