// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// ProfileDao is the manager for logic model data accessing and custom defined data operations functions management.
type ProfileDao struct {
	gmvc.M                // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C      profileColumns // C is the short type for Columns, which contains all the column names of Table for convenient usage.
	DB     gdb.DB         // DB is the raw underlying database management object.
	Table  string         // Table is the underlying table name of the DAO.
}

// ProfileColumns defines and stores column names for table profile.
type profileColumns struct {
	Id        string //
	Uid       string //
	Avatar    string //
	Nickname  string //
	Gender    string //
	Motto     string //
	CreatedAt string //
	UpdatedAt string //
	DeletedAt string //
}

// NewProfileDao creates and returns a new DAO object for table data access.
func NewProfileDao() *ProfileDao {
	columns := profileColumns{
		Id:        "id",
		Uid:       "uid",
		Avatar:    "avatar",
		Nickname:  "nickname",
		Gender:    "gender",
		Motto:     "motto",
		CreatedAt: "created_at",
		UpdatedAt: "updated_at",
		DeletedAt: "deleted_at",
	}
	return &ProfileDao{
		C:     columns,
		M:     g.DB("default").Model("profile").Safe(),
		DB:    g.DB("default"),
		Table: "profile",
	}
}
