// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// TEDao is the manager for logic model data accessing and custom defined data operations functions management.
type TEDao struct {
	gmvc.M           // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C      tEColumns // C is the short type for Columns, which contains all the column names of Table for convenient usage.
	DB     gdb.DB    // DB is the raw underlying database management object.
	Table  string    // Table is the underlying table name of the DAO.
}

// TEColumns defines and stores column names for table t_e.
type tEColumns struct {
	Docs string //
}

// NewTEDao creates and returns a new DAO object for table data access.
func NewTEDao() *TEDao {
	columns := tEColumns{
		Docs: "docs",
	}
	return &TEDao{
		C:     columns,
		M:     g.DB("default").Model("t_e").Safe(),
		DB:    g.DB("default"),
		Table: "t_e",
	}
}
