// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// UserPostLikeDao is the manager for logic model data accessing and custom defined data operations functions management.
type UserPostLikeDao struct {
	gmvc.M                     // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C      userPostLikeColumns // C is the short type for Columns, which contains all the column names of Table for convenient usage.
	DB     gdb.DB              // DB is the raw underlying database management object.
	Table  string              // Table is the underlying table name of the DAO.
}

// UserPostLikeColumns defines and stores column names for table user_post_like.
type userPostLikeColumns struct {
	Id        string //
	Uid       string //
	Pid       string //
	CreatedAt string //
	UpdatedAt string //
	DeletedAt string //
}

// NewUserPostLikeDao creates and returns a new DAO object for table data access.
func NewUserPostLikeDao() *UserPostLikeDao {
	columns := userPostLikeColumns{
		Id:        "id",
		Uid:       "uid",
		Pid:       "pid",
		CreatedAt: "created_at",
		UpdatedAt: "updated_at",
		DeletedAt: "deleted_at",
	}
	return &UserPostLikeDao{
		C:     columns,
		M:     g.DB("default").Model("user_post_like").Safe(),
		DB:    g.DB("default"),
		Table: "user_post_like",
	}
}
